name: Kitsunuki
version: 3.0_1.4.2
description: Default module for the Kitsunuki Minecraft server
author: Alynna
authors: [alynna, alynnafoxie]
main: net.kitsunet.kitsunuki.Kitsune
database: false
softdepend: 
  - Vault
  - Essentials
commands:
   kn:
      description: The extension plugin for the kitsunuki server.
      usage: /<command> [reload|version|save|help]
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   selldrops:
      description: Sell any specially valued drops directly to the server.
      usage: /<command>
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   liquidate:
      description: Sell classes of items.
      usage: /<command> [class]
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   convert:
      description: Convert one item to another.
      usage: /<command> [resource] [amount|all]
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   rep:
      description: Repair an item for a cost in items/money/xp
      usage: /<command> [estimate|confirm|disenhchant]
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   buy:
      description: Buy specific items from the server.
      usage: /<command> [resource] [units]
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   xp:
      description: Get XP information, toggle reporting, make XP bottles
      usage: /<command> [on|off|drink|check|bottle [xp]]
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   wp:
      description: Get and set personal warps.
      usage: /<command> [get|set|{warpname}] [warpname] 
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   ww:
      description: Get info of players online
      usage: /<command> [searchparams]
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   stack:
      description: Make a stack from the item in hand from items in your inventory (up to 64)
      usage: /<command> [limit]
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   roll:
      description: Roll some dice.
      usage: /<command> ndx[+ndx..[+n..]]
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   calc:
      description: Get the server to do your math homework.
      usage: /<command> [expression]
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   chan:
      description: Unsubscribe or subscribe from channels
      usage: /<command> [+|-][channel]
      permission: kitsunuki.default
      permission-message: You don't have <permission>
   bc:
      description: Broadcast globally with the option to turn off.
      usage: /<command> [text]
      permission: kitsunuki.mod
      permission-message: You don't have <permission>
   fileof:
      description: Display the pathname of the region file you are standing in
      usage: /<command> [text]
      permission: kitsunuki.mod
      permission-message: You don't have <permission>
permissions:
   kitsunuki.yes:
      description: Negating this will cause there to be a test for kitsunuki.no.<cmd> to see if a command is accessible.
      default: true
   kitsunuki.default:
      description: The default permissions to do anything.
      default: true
   kitsunuki.player:
      description: Special permissions for registered playahs.
      default: false
   kitsunuki.mod:
      description: Moderator permissions.
      default: op
   kitsunuki.admin:
      description: The default permissions to do almost everything.
      default: op
   kitsunuki.op:
      description: The default permissions to do everything.
      default: op
